/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WarehouseRouteImport } from './routes/warehouse'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WarehouseIndexRouteImport } from './routes/warehouse.index'
import { Route as ProductionIndexRouteImport } from './routes/production.index'
import { Route as OrganizationIndexRouteImport } from './routes/organization.index'
import { Route as WarehouseOpsRouteImport } from './routes/warehouse.ops'
import { Route as ProductionHealthRouteImport } from './routes/production.health'
import { Route as OrganizationTeamRouteImport } from './routes/organization.team'
import { Route as OrganizationRoleRouteImport } from './routes/organization.role'
import { Route as OrganizationPeopleRouteImport } from './routes/organization.people'

const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseIndexRoute = WarehouseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WarehouseRoute,
} as any)
const ProductionIndexRoute = ProductionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductionRoute,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationRoute,
} as any)
const WarehouseOpsRoute = WarehouseOpsRouteImport.update({
  id: '/ops',
  path: '/ops',
  getParentRoute: () => WarehouseRoute,
} as any)
const ProductionHealthRoute = ProductionHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => ProductionRoute,
} as any)
const OrganizationTeamRoute = OrganizationTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationRoleRoute = OrganizationRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationPeopleRoute = OrganizationPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => OrganizationRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/organization': typeof OrganizationRouteWithChildren
  '/production': typeof ProductionRouteWithChildren
  '/settings': typeof SettingsRoute
  '/warehouse': typeof WarehouseRouteWithChildren
  '/organization/people': typeof OrganizationPeopleRoute
  '/organization/role': typeof OrganizationRoleRoute
  '/organization/team': typeof OrganizationTeamRoute
  '/production/health': typeof ProductionHealthRoute
  '/warehouse/ops': typeof WarehouseOpsRoute
  '/organization/': typeof OrganizationIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/warehouse/': typeof WarehouseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/organization/people': typeof OrganizationPeopleRoute
  '/organization/role': typeof OrganizationRoleRoute
  '/organization/team': typeof OrganizationTeamRoute
  '/production/health': typeof ProductionHealthRoute
  '/warehouse/ops': typeof WarehouseOpsRoute
  '/organization': typeof OrganizationIndexRoute
  '/production': typeof ProductionIndexRoute
  '/warehouse': typeof WarehouseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/organization': typeof OrganizationRouteWithChildren
  '/production': typeof ProductionRouteWithChildren
  '/settings': typeof SettingsRoute
  '/warehouse': typeof WarehouseRouteWithChildren
  '/organization/people': typeof OrganizationPeopleRoute
  '/organization/role': typeof OrganizationRoleRoute
  '/organization/team': typeof OrganizationTeamRoute
  '/production/health': typeof ProductionHealthRoute
  '/warehouse/ops': typeof WarehouseOpsRoute
  '/organization/': typeof OrganizationIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/warehouse/': typeof WarehouseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/organization'
    | '/production'
    | '/settings'
    | '/warehouse'
    | '/organization/people'
    | '/organization/role'
    | '/organization/team'
    | '/production/health'
    | '/warehouse/ops'
    | '/organization/'
    | '/production/'
    | '/warehouse/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/organization/people'
    | '/organization/role'
    | '/organization/team'
    | '/production/health'
    | '/warehouse/ops'
    | '/organization'
    | '/production'
    | '/warehouse'
  id:
    | '__root__'
    | '/'
    | '/organization'
    | '/production'
    | '/settings'
    | '/warehouse'
    | '/organization/people'
    | '/organization/role'
    | '/organization/team'
    | '/production/health'
    | '/warehouse/ops'
    | '/organization/'
    | '/production/'
    | '/warehouse/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrganizationRoute: typeof OrganizationRouteWithChildren
  ProductionRoute: typeof ProductionRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  WarehouseRoute: typeof WarehouseRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/': {
      id: '/warehouse/'
      path: '/'
      fullPath: '/warehouse/'
      preLoaderRoute: typeof WarehouseIndexRouteImport
      parentRoute: typeof WarehouseRoute
    }
    '/production/': {
      id: '/production/'
      path: '/'
      fullPath: '/production/'
      preLoaderRoute: typeof ProductionIndexRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/organization/': {
      id: '/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/warehouse/ops': {
      id: '/warehouse/ops'
      path: '/ops'
      fullPath: '/warehouse/ops'
      preLoaderRoute: typeof WarehouseOpsRouteImport
      parentRoute: typeof WarehouseRoute
    }
    '/production/health': {
      id: '/production/health'
      path: '/health'
      fullPath: '/production/health'
      preLoaderRoute: typeof ProductionHealthRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/organization/team': {
      id: '/organization/team'
      path: '/team'
      fullPath: '/organization/team'
      preLoaderRoute: typeof OrganizationTeamRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/role': {
      id: '/organization/role'
      path: '/role'
      fullPath: '/organization/role'
      preLoaderRoute: typeof OrganizationRoleRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/people': {
      id: '/organization/people'
      path: '/people'
      fullPath: '/organization/people'
      preLoaderRoute: typeof OrganizationPeopleRouteImport
      parentRoute: typeof OrganizationRoute
    }
  }
}

interface OrganizationRouteChildren {
  OrganizationPeopleRoute: typeof OrganizationPeopleRoute
  OrganizationRoleRoute: typeof OrganizationRoleRoute
  OrganizationTeamRoute: typeof OrganizationTeamRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
}

const OrganizationRouteChildren: OrganizationRouteChildren = {
  OrganizationPeopleRoute: OrganizationPeopleRoute,
  OrganizationRoleRoute: OrganizationRoleRoute,
  OrganizationTeamRoute: OrganizationTeamRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
}

const OrganizationRouteWithChildren = OrganizationRoute._addFileChildren(
  OrganizationRouteChildren,
)

interface ProductionRouteChildren {
  ProductionHealthRoute: typeof ProductionHealthRoute
  ProductionIndexRoute: typeof ProductionIndexRoute
}

const ProductionRouteChildren: ProductionRouteChildren = {
  ProductionHealthRoute: ProductionHealthRoute,
  ProductionIndexRoute: ProductionIndexRoute,
}

const ProductionRouteWithChildren = ProductionRoute._addFileChildren(
  ProductionRouteChildren,
)

interface WarehouseRouteChildren {
  WarehouseOpsRoute: typeof WarehouseOpsRoute
  WarehouseIndexRoute: typeof WarehouseIndexRoute
}

const WarehouseRouteChildren: WarehouseRouteChildren = {
  WarehouseOpsRoute: WarehouseOpsRoute,
  WarehouseIndexRoute: WarehouseIndexRoute,
}

const WarehouseRouteWithChildren = WarehouseRoute._addFileChildren(
  WarehouseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrganizationRoute: OrganizationRouteWithChildren,
  ProductionRoute: ProductionRouteWithChildren,
  SettingsRoute: SettingsRoute,
  WarehouseRoute: WarehouseRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
