/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as WarehouseRouteImport } from './routes/warehouse'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as OrganizationRouteImport } from './routes/organization'
import { Route as MRouteImport } from './routes/m'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as ArchiveRouteImport } from './routes/archive'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WarehouseIndexRouteImport } from './routes/warehouse.index'
import { Route as SettingsIndexRouteImport } from './routes/settings.index'
import { Route as ProductionIndexRouteImport } from './routes/production.index'
import { Route as OrganizationIndexRouteImport } from './routes/organization.index'
import { Route as MIndexRouteImport } from './routes/m.index'
import { Route as WarehouseTransferRouteImport } from './routes/warehouse.transfer'
import { Route as WarehouseLossRouteImport } from './routes/warehouse.loss'
import { Route as WarehouseDrugRouteImport } from './routes/warehouse.drug'
import { Route as WarehouseDispenseRouteImport } from './routes/warehouse.dispense'
import { Route as SettingsRulesRouteImport } from './routes/settings.rules'
import { Route as SettingsKnowledgeRouteImport } from './routes/settings.knowledge'
import { Route as ProductionVaccineRouteImport } from './routes/production.vaccine'
import { Route as ProductionPostpartumRouteImport } from './routes/production.postpartum'
import { Route as ProductionPlansRouteImport } from './routes/production.plans'
import { Route as ProductionHoofRouteImport } from './routes/production.hoof'
import { Route as ProductionGeneralRouteImport } from './routes/production.general'
import { Route as ProductionFeedbackRouteImport } from './routes/production.feedback'
import { Route as ProductionDryingRouteImport } from './routes/production.drying'
import { Route as ProductionDiseaseRouteImport } from './routes/production.disease'
import { Route as ProductionDewormRouteImport } from './routes/production.deworm'
import { Route as OrganizationTenantRouteImport } from './routes/organization.tenant'
import { Route as OrganizationTeamRouteImport } from './routes/organization.team'
import { Route as OrganizationRoleRouteImport } from './routes/organization.role'
import { Route as OrganizationAccountRouteImport } from './routes/organization.account'
import { Route as MWorkspaceRouteImport } from './routes/m.workspace'
import { Route as MScanRouteImport } from './routes/m.scan'
import { Route as MReportRouteImport } from './routes/m.report'
import { Route as MNotificationsRouteImport } from './routes/m.notifications'
import { Route as MMeRouteImport } from './routes/m.me'
import { Route as MLoginRouteImport } from './routes/m.login'
import { Route as KnowledgeSymptomRouteImport } from './routes/knowledge.symptom'
import { Route as KnowledgePrescriptionRouteImport } from './routes/knowledge.prescription'
import { Route as KnowledgeDiseaseRouteImport } from './routes/knowledge.disease'
import { Route as ArchiveFarmRouteImport } from './routes/archive.farm'
import { Route as ArchiveCattleRouteImport } from './routes/archive.cattle'
import { Route as ArchiveBarnRouteImport } from './routes/archive.barn'
import { Route as MHealthIndexRouteImport } from './routes/m.health.index'
import { Route as MAnimalsIndexRouteImport } from './routes/m.animals.index'
import { Route as MHealthIdRouteImport } from './routes/m.health.$id'
import { Route as MBarnsIdRouteImport } from './routes/m.barns.$id'
import { Route as MAnimalsIdRouteImport } from './routes/m.animals.$id'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseRoute = WarehouseRouteImport.update({
  id: '/warehouse',
  path: '/warehouse',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationRoute = OrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => rootRouteImport,
} as any)
const MRoute = MRouteImport.update({
  id: '/m',
  path: '/m',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchiveRoute = ArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WarehouseIndexRoute = WarehouseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WarehouseRoute,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRoute,
} as any)
const ProductionIndexRoute = ProductionIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductionRoute,
} as any)
const OrganizationIndexRoute = OrganizationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizationRoute,
} as any)
const MIndexRoute = MIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MRoute,
} as any)
const WarehouseTransferRoute = WarehouseTransferRouteImport.update({
  id: '/transfer',
  path: '/transfer',
  getParentRoute: () => WarehouseRoute,
} as any)
const WarehouseLossRoute = WarehouseLossRouteImport.update({
  id: '/loss',
  path: '/loss',
  getParentRoute: () => WarehouseRoute,
} as any)
const WarehouseDrugRoute = WarehouseDrugRouteImport.update({
  id: '/drug',
  path: '/drug',
  getParentRoute: () => WarehouseRoute,
} as any)
const WarehouseDispenseRoute = WarehouseDispenseRouteImport.update({
  id: '/dispense',
  path: '/dispense',
  getParentRoute: () => WarehouseRoute,
} as any)
const SettingsRulesRoute = SettingsRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => SettingsRoute,
} as any)
const SettingsKnowledgeRoute = SettingsKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => SettingsRoute,
} as any)
const ProductionVaccineRoute = ProductionVaccineRouteImport.update({
  id: '/vaccine',
  path: '/vaccine',
  getParentRoute: () => ProductionRoute,
} as any)
const ProductionPostpartumRoute = ProductionPostpartumRouteImport.update({
  id: '/postpartum',
  path: '/postpartum',
  getParentRoute: () => ProductionRoute,
} as any)
const ProductionPlansRoute = ProductionPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => ProductionRoute,
} as any)
const ProductionHoofRoute = ProductionHoofRouteImport.update({
  id: '/hoof',
  path: '/hoof',
  getParentRoute: () => ProductionRoute,
} as any)
const ProductionGeneralRoute = ProductionGeneralRouteImport.update({
  id: '/general',
  path: '/general',
  getParentRoute: () => ProductionRoute,
} as any)
const ProductionFeedbackRoute = ProductionFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => ProductionRoute,
} as any)
const ProductionDryingRoute = ProductionDryingRouteImport.update({
  id: '/drying',
  path: '/drying',
  getParentRoute: () => ProductionRoute,
} as any)
const ProductionDiseaseRoute = ProductionDiseaseRouteImport.update({
  id: '/disease',
  path: '/disease',
  getParentRoute: () => ProductionRoute,
} as any)
const ProductionDewormRoute = ProductionDewormRouteImport.update({
  id: '/deworm',
  path: '/deworm',
  getParentRoute: () => ProductionRoute,
} as any)
const OrganizationTenantRoute = OrganizationTenantRouteImport.update({
  id: '/tenant',
  path: '/tenant',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationTeamRoute = OrganizationTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationRoleRoute = OrganizationRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => OrganizationRoute,
} as any)
const OrganizationAccountRoute = OrganizationAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => OrganizationRoute,
} as any)
const MWorkspaceRoute = MWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => MRoute,
} as any)
const MScanRoute = MScanRouteImport.update({
  id: '/scan',
  path: '/scan',
  getParentRoute: () => MRoute,
} as any)
const MReportRoute = MReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => MRoute,
} as any)
const MNotificationsRoute = MNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => MRoute,
} as any)
const MMeRoute = MMeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => MRoute,
} as any)
const MLoginRoute = MLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => MRoute,
} as any)
const KnowledgeSymptomRoute = KnowledgeSymptomRouteImport.update({
  id: '/symptom',
  path: '/symptom',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgePrescriptionRoute = KnowledgePrescriptionRouteImport.update({
  id: '/prescription',
  path: '/prescription',
  getParentRoute: () => KnowledgeRoute,
} as any)
const KnowledgeDiseaseRoute = KnowledgeDiseaseRouteImport.update({
  id: '/disease',
  path: '/disease',
  getParentRoute: () => KnowledgeRoute,
} as any)
const ArchiveFarmRoute = ArchiveFarmRouteImport.update({
  id: '/farm',
  path: '/farm',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchiveCattleRoute = ArchiveCattleRouteImport.update({
  id: '/cattle',
  path: '/cattle',
  getParentRoute: () => ArchiveRoute,
} as any)
const ArchiveBarnRoute = ArchiveBarnRouteImport.update({
  id: '/barn',
  path: '/barn',
  getParentRoute: () => ArchiveRoute,
} as any)
const MHealthIndexRoute = MHealthIndexRouteImport.update({
  id: '/health/',
  path: '/health/',
  getParentRoute: () => MRoute,
} as any)
const MAnimalsIndexRoute = MAnimalsIndexRouteImport.update({
  id: '/animals/',
  path: '/animals/',
  getParentRoute: () => MRoute,
} as any)
const MHealthIdRoute = MHealthIdRouteImport.update({
  id: '/health/$id',
  path: '/health/$id',
  getParentRoute: () => MRoute,
} as any)
const MBarnsIdRoute = MBarnsIdRouteImport.update({
  id: '/barns/$id',
  path: '/barns/$id',
  getParentRoute: () => MRoute,
} as any)
const MAnimalsIdRoute = MAnimalsIdRouteImport.update({
  id: '/animals/$id',
  path: '/animals/$id',
  getParentRoute: () => MRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/login': typeof LoginRoute
  '/m': typeof MRouteWithChildren
  '/organization': typeof OrganizationRouteWithChildren
  '/production': typeof ProductionRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/warehouse': typeof WarehouseRouteWithChildren
  '/workspace': typeof WorkspaceRoute
  '/archive/barn': typeof ArchiveBarnRoute
  '/archive/cattle': typeof ArchiveCattleRoute
  '/archive/farm': typeof ArchiveFarmRoute
  '/knowledge/disease': typeof KnowledgeDiseaseRoute
  '/knowledge/prescription': typeof KnowledgePrescriptionRoute
  '/knowledge/symptom': typeof KnowledgeSymptomRoute
  '/m/login': typeof MLoginRoute
  '/m/me': typeof MMeRoute
  '/m/notifications': typeof MNotificationsRoute
  '/m/report': typeof MReportRoute
  '/m/scan': typeof MScanRoute
  '/m/workspace': typeof MWorkspaceRoute
  '/organization/account': typeof OrganizationAccountRoute
  '/organization/role': typeof OrganizationRoleRoute
  '/organization/team': typeof OrganizationTeamRoute
  '/organization/tenant': typeof OrganizationTenantRoute
  '/production/deworm': typeof ProductionDewormRoute
  '/production/disease': typeof ProductionDiseaseRoute
  '/production/drying': typeof ProductionDryingRoute
  '/production/feedback': typeof ProductionFeedbackRoute
  '/production/general': typeof ProductionGeneralRoute
  '/production/hoof': typeof ProductionHoofRoute
  '/production/plans': typeof ProductionPlansRoute
  '/production/postpartum': typeof ProductionPostpartumRoute
  '/production/vaccine': typeof ProductionVaccineRoute
  '/settings/knowledge': typeof SettingsKnowledgeRoute
  '/settings/rules': typeof SettingsRulesRoute
  '/warehouse/dispense': typeof WarehouseDispenseRoute
  '/warehouse/drug': typeof WarehouseDrugRoute
  '/warehouse/loss': typeof WarehouseLossRoute
  '/warehouse/transfer': typeof WarehouseTransferRoute
  '/m/': typeof MIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/warehouse/': typeof WarehouseIndexRoute
  '/m/animals/$id': typeof MAnimalsIdRoute
  '/m/barns/$id': typeof MBarnsIdRoute
  '/m/health/$id': typeof MHealthIdRoute
  '/m/animals/': typeof MAnimalsIndexRoute
  '/m/health/': typeof MHealthIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/login': typeof LoginRoute
  '/workspace': typeof WorkspaceRoute
  '/archive/barn': typeof ArchiveBarnRoute
  '/archive/cattle': typeof ArchiveCattleRoute
  '/archive/farm': typeof ArchiveFarmRoute
  '/knowledge/disease': typeof KnowledgeDiseaseRoute
  '/knowledge/prescription': typeof KnowledgePrescriptionRoute
  '/knowledge/symptom': typeof KnowledgeSymptomRoute
  '/m/login': typeof MLoginRoute
  '/m/me': typeof MMeRoute
  '/m/notifications': typeof MNotificationsRoute
  '/m/report': typeof MReportRoute
  '/m/scan': typeof MScanRoute
  '/m/workspace': typeof MWorkspaceRoute
  '/organization/account': typeof OrganizationAccountRoute
  '/organization/role': typeof OrganizationRoleRoute
  '/organization/team': typeof OrganizationTeamRoute
  '/organization/tenant': typeof OrganizationTenantRoute
  '/production/deworm': typeof ProductionDewormRoute
  '/production/disease': typeof ProductionDiseaseRoute
  '/production/drying': typeof ProductionDryingRoute
  '/production/feedback': typeof ProductionFeedbackRoute
  '/production/general': typeof ProductionGeneralRoute
  '/production/hoof': typeof ProductionHoofRoute
  '/production/plans': typeof ProductionPlansRoute
  '/production/postpartum': typeof ProductionPostpartumRoute
  '/production/vaccine': typeof ProductionVaccineRoute
  '/settings/knowledge': typeof SettingsKnowledgeRoute
  '/settings/rules': typeof SettingsRulesRoute
  '/warehouse/dispense': typeof WarehouseDispenseRoute
  '/warehouse/drug': typeof WarehouseDrugRoute
  '/warehouse/loss': typeof WarehouseLossRoute
  '/warehouse/transfer': typeof WarehouseTransferRoute
  '/m': typeof MIndexRoute
  '/organization': typeof OrganizationIndexRoute
  '/production': typeof ProductionIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/warehouse': typeof WarehouseIndexRoute
  '/m/animals/$id': typeof MAnimalsIdRoute
  '/m/barns/$id': typeof MBarnsIdRoute
  '/m/health/$id': typeof MHealthIdRoute
  '/m/animals': typeof MAnimalsIndexRoute
  '/m/health': typeof MHealthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/archive': typeof ArchiveRouteWithChildren
  '/knowledge': typeof KnowledgeRouteWithChildren
  '/login': typeof LoginRoute
  '/m': typeof MRouteWithChildren
  '/organization': typeof OrganizationRouteWithChildren
  '/production': typeof ProductionRouteWithChildren
  '/settings': typeof SettingsRouteWithChildren
  '/warehouse': typeof WarehouseRouteWithChildren
  '/workspace': typeof WorkspaceRoute
  '/archive/barn': typeof ArchiveBarnRoute
  '/archive/cattle': typeof ArchiveCattleRoute
  '/archive/farm': typeof ArchiveFarmRoute
  '/knowledge/disease': typeof KnowledgeDiseaseRoute
  '/knowledge/prescription': typeof KnowledgePrescriptionRoute
  '/knowledge/symptom': typeof KnowledgeSymptomRoute
  '/m/login': typeof MLoginRoute
  '/m/me': typeof MMeRoute
  '/m/notifications': typeof MNotificationsRoute
  '/m/report': typeof MReportRoute
  '/m/scan': typeof MScanRoute
  '/m/workspace': typeof MWorkspaceRoute
  '/organization/account': typeof OrganizationAccountRoute
  '/organization/role': typeof OrganizationRoleRoute
  '/organization/team': typeof OrganizationTeamRoute
  '/organization/tenant': typeof OrganizationTenantRoute
  '/production/deworm': typeof ProductionDewormRoute
  '/production/disease': typeof ProductionDiseaseRoute
  '/production/drying': typeof ProductionDryingRoute
  '/production/feedback': typeof ProductionFeedbackRoute
  '/production/general': typeof ProductionGeneralRoute
  '/production/hoof': typeof ProductionHoofRoute
  '/production/plans': typeof ProductionPlansRoute
  '/production/postpartum': typeof ProductionPostpartumRoute
  '/production/vaccine': typeof ProductionVaccineRoute
  '/settings/knowledge': typeof SettingsKnowledgeRoute
  '/settings/rules': typeof SettingsRulesRoute
  '/warehouse/dispense': typeof WarehouseDispenseRoute
  '/warehouse/drug': typeof WarehouseDrugRoute
  '/warehouse/loss': typeof WarehouseLossRoute
  '/warehouse/transfer': typeof WarehouseTransferRoute
  '/m/': typeof MIndexRoute
  '/organization/': typeof OrganizationIndexRoute
  '/production/': typeof ProductionIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/warehouse/': typeof WarehouseIndexRoute
  '/m/animals/$id': typeof MAnimalsIdRoute
  '/m/barns/$id': typeof MBarnsIdRoute
  '/m/health/$id': typeof MHealthIdRoute
  '/m/animals/': typeof MAnimalsIndexRoute
  '/m/health/': typeof MHealthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/archive'
    | '/knowledge'
    | '/login'
    | '/m'
    | '/organization'
    | '/production'
    | '/settings'
    | '/warehouse'
    | '/workspace'
    | '/archive/barn'
    | '/archive/cattle'
    | '/archive/farm'
    | '/knowledge/disease'
    | '/knowledge/prescription'
    | '/knowledge/symptom'
    | '/m/login'
    | '/m/me'
    | '/m/notifications'
    | '/m/report'
    | '/m/scan'
    | '/m/workspace'
    | '/organization/account'
    | '/organization/role'
    | '/organization/team'
    | '/organization/tenant'
    | '/production/deworm'
    | '/production/disease'
    | '/production/drying'
    | '/production/feedback'
    | '/production/general'
    | '/production/hoof'
    | '/production/plans'
    | '/production/postpartum'
    | '/production/vaccine'
    | '/settings/knowledge'
    | '/settings/rules'
    | '/warehouse/dispense'
    | '/warehouse/drug'
    | '/warehouse/loss'
    | '/warehouse/transfer'
    | '/m/'
    | '/organization/'
    | '/production/'
    | '/settings/'
    | '/warehouse/'
    | '/m/animals/$id'
    | '/m/barns/$id'
    | '/m/health/$id'
    | '/m/animals/'
    | '/m/health/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/archive'
    | '/knowledge'
    | '/login'
    | '/workspace'
    | '/archive/barn'
    | '/archive/cattle'
    | '/archive/farm'
    | '/knowledge/disease'
    | '/knowledge/prescription'
    | '/knowledge/symptom'
    | '/m/login'
    | '/m/me'
    | '/m/notifications'
    | '/m/report'
    | '/m/scan'
    | '/m/workspace'
    | '/organization/account'
    | '/organization/role'
    | '/organization/team'
    | '/organization/tenant'
    | '/production/deworm'
    | '/production/disease'
    | '/production/drying'
    | '/production/feedback'
    | '/production/general'
    | '/production/hoof'
    | '/production/plans'
    | '/production/postpartum'
    | '/production/vaccine'
    | '/settings/knowledge'
    | '/settings/rules'
    | '/warehouse/dispense'
    | '/warehouse/drug'
    | '/warehouse/loss'
    | '/warehouse/transfer'
    | '/m'
    | '/organization'
    | '/production'
    | '/settings'
    | '/warehouse'
    | '/m/animals/$id'
    | '/m/barns/$id'
    | '/m/health/$id'
    | '/m/animals'
    | '/m/health'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/archive'
    | '/knowledge'
    | '/login'
    | '/m'
    | '/organization'
    | '/production'
    | '/settings'
    | '/warehouse'
    | '/workspace'
    | '/archive/barn'
    | '/archive/cattle'
    | '/archive/farm'
    | '/knowledge/disease'
    | '/knowledge/prescription'
    | '/knowledge/symptom'
    | '/m/login'
    | '/m/me'
    | '/m/notifications'
    | '/m/report'
    | '/m/scan'
    | '/m/workspace'
    | '/organization/account'
    | '/organization/role'
    | '/organization/team'
    | '/organization/tenant'
    | '/production/deworm'
    | '/production/disease'
    | '/production/drying'
    | '/production/feedback'
    | '/production/general'
    | '/production/hoof'
    | '/production/plans'
    | '/production/postpartum'
    | '/production/vaccine'
    | '/settings/knowledge'
    | '/settings/rules'
    | '/warehouse/dispense'
    | '/warehouse/drug'
    | '/warehouse/loss'
    | '/warehouse/transfer'
    | '/m/'
    | '/organization/'
    | '/production/'
    | '/settings/'
    | '/warehouse/'
    | '/m/animals/$id'
    | '/m/barns/$id'
    | '/m/health/$id'
    | '/m/animals/'
    | '/m/health/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ArchiveRoute: typeof ArchiveRouteWithChildren
  KnowledgeRoute: typeof KnowledgeRouteWithChildren
  LoginRoute: typeof LoginRoute
  MRoute: typeof MRouteWithChildren
  OrganizationRoute: typeof OrganizationRouteWithChildren
  ProductionRoute: typeof ProductionRouteWithChildren
  SettingsRoute: typeof SettingsRouteWithChildren
  WarehouseRoute: typeof WarehouseRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse': {
      id: '/warehouse'
      path: '/warehouse'
      fullPath: '/warehouse'
      preLoaderRoute: typeof WarehouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization': {
      id: '/organization'
      path: '/organization'
      fullPath: '/organization'
      preLoaderRoute: typeof OrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m': {
      id: '/m'
      path: '/m'
      fullPath: '/m'
      preLoaderRoute: typeof MRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/archive': {
      id: '/archive'
      path: '/archive'
      fullPath: '/archive'
      preLoaderRoute: typeof ArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warehouse/': {
      id: '/warehouse/'
      path: '/'
      fullPath: '/warehouse/'
      preLoaderRoute: typeof WarehouseIndexRouteImport
      parentRoute: typeof WarehouseRoute
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/production/': {
      id: '/production/'
      path: '/'
      fullPath: '/production/'
      preLoaderRoute: typeof ProductionIndexRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/organization/': {
      id: '/organization/'
      path: '/'
      fullPath: '/organization/'
      preLoaderRoute: typeof OrganizationIndexRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/m/': {
      id: '/m/'
      path: '/'
      fullPath: '/m/'
      preLoaderRoute: typeof MIndexRouteImport
      parentRoute: typeof MRoute
    }
    '/warehouse/transfer': {
      id: '/warehouse/transfer'
      path: '/transfer'
      fullPath: '/warehouse/transfer'
      preLoaderRoute: typeof WarehouseTransferRouteImport
      parentRoute: typeof WarehouseRoute
    }
    '/warehouse/loss': {
      id: '/warehouse/loss'
      path: '/loss'
      fullPath: '/warehouse/loss'
      preLoaderRoute: typeof WarehouseLossRouteImport
      parentRoute: typeof WarehouseRoute
    }
    '/warehouse/drug': {
      id: '/warehouse/drug'
      path: '/drug'
      fullPath: '/warehouse/drug'
      preLoaderRoute: typeof WarehouseDrugRouteImport
      parentRoute: typeof WarehouseRoute
    }
    '/warehouse/dispense': {
      id: '/warehouse/dispense'
      path: '/dispense'
      fullPath: '/warehouse/dispense'
      preLoaderRoute: typeof WarehouseDispenseRouteImport
      parentRoute: typeof WarehouseRoute
    }
    '/settings/rules': {
      id: '/settings/rules'
      path: '/rules'
      fullPath: '/settings/rules'
      preLoaderRoute: typeof SettingsRulesRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/settings/knowledge': {
      id: '/settings/knowledge'
      path: '/knowledge'
      fullPath: '/settings/knowledge'
      preLoaderRoute: typeof SettingsKnowledgeRouteImport
      parentRoute: typeof SettingsRoute
    }
    '/production/vaccine': {
      id: '/production/vaccine'
      path: '/vaccine'
      fullPath: '/production/vaccine'
      preLoaderRoute: typeof ProductionVaccineRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/production/postpartum': {
      id: '/production/postpartum'
      path: '/postpartum'
      fullPath: '/production/postpartum'
      preLoaderRoute: typeof ProductionPostpartumRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/production/plans': {
      id: '/production/plans'
      path: '/plans'
      fullPath: '/production/plans'
      preLoaderRoute: typeof ProductionPlansRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/production/hoof': {
      id: '/production/hoof'
      path: '/hoof'
      fullPath: '/production/hoof'
      preLoaderRoute: typeof ProductionHoofRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/production/general': {
      id: '/production/general'
      path: '/general'
      fullPath: '/production/general'
      preLoaderRoute: typeof ProductionGeneralRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/production/feedback': {
      id: '/production/feedback'
      path: '/feedback'
      fullPath: '/production/feedback'
      preLoaderRoute: typeof ProductionFeedbackRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/production/drying': {
      id: '/production/drying'
      path: '/drying'
      fullPath: '/production/drying'
      preLoaderRoute: typeof ProductionDryingRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/production/disease': {
      id: '/production/disease'
      path: '/disease'
      fullPath: '/production/disease'
      preLoaderRoute: typeof ProductionDiseaseRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/production/deworm': {
      id: '/production/deworm'
      path: '/deworm'
      fullPath: '/production/deworm'
      preLoaderRoute: typeof ProductionDewormRouteImport
      parentRoute: typeof ProductionRoute
    }
    '/organization/tenant': {
      id: '/organization/tenant'
      path: '/tenant'
      fullPath: '/organization/tenant'
      preLoaderRoute: typeof OrganizationTenantRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/team': {
      id: '/organization/team'
      path: '/team'
      fullPath: '/organization/team'
      preLoaderRoute: typeof OrganizationTeamRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/role': {
      id: '/organization/role'
      path: '/role'
      fullPath: '/organization/role'
      preLoaderRoute: typeof OrganizationRoleRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/organization/account': {
      id: '/organization/account'
      path: '/account'
      fullPath: '/organization/account'
      preLoaderRoute: typeof OrganizationAccountRouteImport
      parentRoute: typeof OrganizationRoute
    }
    '/m/workspace': {
      id: '/m/workspace'
      path: '/workspace'
      fullPath: '/m/workspace'
      preLoaderRoute: typeof MWorkspaceRouteImport
      parentRoute: typeof MRoute
    }
    '/m/scan': {
      id: '/m/scan'
      path: '/scan'
      fullPath: '/m/scan'
      preLoaderRoute: typeof MScanRouteImport
      parentRoute: typeof MRoute
    }
    '/m/report': {
      id: '/m/report'
      path: '/report'
      fullPath: '/m/report'
      preLoaderRoute: typeof MReportRouteImport
      parentRoute: typeof MRoute
    }
    '/m/notifications': {
      id: '/m/notifications'
      path: '/notifications'
      fullPath: '/m/notifications'
      preLoaderRoute: typeof MNotificationsRouteImport
      parentRoute: typeof MRoute
    }
    '/m/me': {
      id: '/m/me'
      path: '/me'
      fullPath: '/m/me'
      preLoaderRoute: typeof MMeRouteImport
      parentRoute: typeof MRoute
    }
    '/m/login': {
      id: '/m/login'
      path: '/login'
      fullPath: '/m/login'
      preLoaderRoute: typeof MLoginRouteImport
      parentRoute: typeof MRoute
    }
    '/knowledge/symptom': {
      id: '/knowledge/symptom'
      path: '/symptom'
      fullPath: '/knowledge/symptom'
      preLoaderRoute: typeof KnowledgeSymptomRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/prescription': {
      id: '/knowledge/prescription'
      path: '/prescription'
      fullPath: '/knowledge/prescription'
      preLoaderRoute: typeof KnowledgePrescriptionRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/knowledge/disease': {
      id: '/knowledge/disease'
      path: '/disease'
      fullPath: '/knowledge/disease'
      preLoaderRoute: typeof KnowledgeDiseaseRouteImport
      parentRoute: typeof KnowledgeRoute
    }
    '/archive/farm': {
      id: '/archive/farm'
      path: '/farm'
      fullPath: '/archive/farm'
      preLoaderRoute: typeof ArchiveFarmRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/cattle': {
      id: '/archive/cattle'
      path: '/cattle'
      fullPath: '/archive/cattle'
      preLoaderRoute: typeof ArchiveCattleRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/archive/barn': {
      id: '/archive/barn'
      path: '/barn'
      fullPath: '/archive/barn'
      preLoaderRoute: typeof ArchiveBarnRouteImport
      parentRoute: typeof ArchiveRoute
    }
    '/m/health/': {
      id: '/m/health/'
      path: '/health'
      fullPath: '/m/health/'
      preLoaderRoute: typeof MHealthIndexRouteImport
      parentRoute: typeof MRoute
    }
    '/m/animals/': {
      id: '/m/animals/'
      path: '/animals'
      fullPath: '/m/animals/'
      preLoaderRoute: typeof MAnimalsIndexRouteImport
      parentRoute: typeof MRoute
    }
    '/m/health/$id': {
      id: '/m/health/$id'
      path: '/health/$id'
      fullPath: '/m/health/$id'
      preLoaderRoute: typeof MHealthIdRouteImport
      parentRoute: typeof MRoute
    }
    '/m/barns/$id': {
      id: '/m/barns/$id'
      path: '/barns/$id'
      fullPath: '/m/barns/$id'
      preLoaderRoute: typeof MBarnsIdRouteImport
      parentRoute: typeof MRoute
    }
    '/m/animals/$id': {
      id: '/m/animals/$id'
      path: '/animals/$id'
      fullPath: '/m/animals/$id'
      preLoaderRoute: typeof MAnimalsIdRouteImport
      parentRoute: typeof MRoute
    }
  }
}

interface ArchiveRouteChildren {
  ArchiveBarnRoute: typeof ArchiveBarnRoute
  ArchiveCattleRoute: typeof ArchiveCattleRoute
  ArchiveFarmRoute: typeof ArchiveFarmRoute
}

const ArchiveRouteChildren: ArchiveRouteChildren = {
  ArchiveBarnRoute: ArchiveBarnRoute,
  ArchiveCattleRoute: ArchiveCattleRoute,
  ArchiveFarmRoute: ArchiveFarmRoute,
}

const ArchiveRouteWithChildren =
  ArchiveRoute._addFileChildren(ArchiveRouteChildren)

interface KnowledgeRouteChildren {
  KnowledgeDiseaseRoute: typeof KnowledgeDiseaseRoute
  KnowledgePrescriptionRoute: typeof KnowledgePrescriptionRoute
  KnowledgeSymptomRoute: typeof KnowledgeSymptomRoute
}

const KnowledgeRouteChildren: KnowledgeRouteChildren = {
  KnowledgeDiseaseRoute: KnowledgeDiseaseRoute,
  KnowledgePrescriptionRoute: KnowledgePrescriptionRoute,
  KnowledgeSymptomRoute: KnowledgeSymptomRoute,
}

const KnowledgeRouteWithChildren = KnowledgeRoute._addFileChildren(
  KnowledgeRouteChildren,
)

interface MRouteChildren {
  MLoginRoute: typeof MLoginRoute
  MMeRoute: typeof MMeRoute
  MNotificationsRoute: typeof MNotificationsRoute
  MReportRoute: typeof MReportRoute
  MScanRoute: typeof MScanRoute
  MWorkspaceRoute: typeof MWorkspaceRoute
  MIndexRoute: typeof MIndexRoute
  MAnimalsIdRoute: typeof MAnimalsIdRoute
  MBarnsIdRoute: typeof MBarnsIdRoute
  MHealthIdRoute: typeof MHealthIdRoute
  MAnimalsIndexRoute: typeof MAnimalsIndexRoute
  MHealthIndexRoute: typeof MHealthIndexRoute
}

const MRouteChildren: MRouteChildren = {
  MLoginRoute: MLoginRoute,
  MMeRoute: MMeRoute,
  MNotificationsRoute: MNotificationsRoute,
  MReportRoute: MReportRoute,
  MScanRoute: MScanRoute,
  MWorkspaceRoute: MWorkspaceRoute,
  MIndexRoute: MIndexRoute,
  MAnimalsIdRoute: MAnimalsIdRoute,
  MBarnsIdRoute: MBarnsIdRoute,
  MHealthIdRoute: MHealthIdRoute,
  MAnimalsIndexRoute: MAnimalsIndexRoute,
  MHealthIndexRoute: MHealthIndexRoute,
}

const MRouteWithChildren = MRoute._addFileChildren(MRouteChildren)

interface OrganizationRouteChildren {
  OrganizationAccountRoute: typeof OrganizationAccountRoute
  OrganizationRoleRoute: typeof OrganizationRoleRoute
  OrganizationTeamRoute: typeof OrganizationTeamRoute
  OrganizationTenantRoute: typeof OrganizationTenantRoute
  OrganizationIndexRoute: typeof OrganizationIndexRoute
}

const OrganizationRouteChildren: OrganizationRouteChildren = {
  OrganizationAccountRoute: OrganizationAccountRoute,
  OrganizationRoleRoute: OrganizationRoleRoute,
  OrganizationTeamRoute: OrganizationTeamRoute,
  OrganizationTenantRoute: OrganizationTenantRoute,
  OrganizationIndexRoute: OrganizationIndexRoute,
}

const OrganizationRouteWithChildren = OrganizationRoute._addFileChildren(
  OrganizationRouteChildren,
)

interface ProductionRouteChildren {
  ProductionDewormRoute: typeof ProductionDewormRoute
  ProductionDiseaseRoute: typeof ProductionDiseaseRoute
  ProductionDryingRoute: typeof ProductionDryingRoute
  ProductionFeedbackRoute: typeof ProductionFeedbackRoute
  ProductionGeneralRoute: typeof ProductionGeneralRoute
  ProductionHoofRoute: typeof ProductionHoofRoute
  ProductionPlansRoute: typeof ProductionPlansRoute
  ProductionPostpartumRoute: typeof ProductionPostpartumRoute
  ProductionVaccineRoute: typeof ProductionVaccineRoute
  ProductionIndexRoute: typeof ProductionIndexRoute
}

const ProductionRouteChildren: ProductionRouteChildren = {
  ProductionDewormRoute: ProductionDewormRoute,
  ProductionDiseaseRoute: ProductionDiseaseRoute,
  ProductionDryingRoute: ProductionDryingRoute,
  ProductionFeedbackRoute: ProductionFeedbackRoute,
  ProductionGeneralRoute: ProductionGeneralRoute,
  ProductionHoofRoute: ProductionHoofRoute,
  ProductionPlansRoute: ProductionPlansRoute,
  ProductionPostpartumRoute: ProductionPostpartumRoute,
  ProductionVaccineRoute: ProductionVaccineRoute,
  ProductionIndexRoute: ProductionIndexRoute,
}

const ProductionRouteWithChildren = ProductionRoute._addFileChildren(
  ProductionRouteChildren,
)

interface SettingsRouteChildren {
  SettingsKnowledgeRoute: typeof SettingsKnowledgeRoute
  SettingsRulesRoute: typeof SettingsRulesRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteChildren: SettingsRouteChildren = {
  SettingsKnowledgeRoute: SettingsKnowledgeRoute,
  SettingsRulesRoute: SettingsRulesRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteWithChildren = SettingsRoute._addFileChildren(
  SettingsRouteChildren,
)

interface WarehouseRouteChildren {
  WarehouseDispenseRoute: typeof WarehouseDispenseRoute
  WarehouseDrugRoute: typeof WarehouseDrugRoute
  WarehouseLossRoute: typeof WarehouseLossRoute
  WarehouseTransferRoute: typeof WarehouseTransferRoute
  WarehouseIndexRoute: typeof WarehouseIndexRoute
}

const WarehouseRouteChildren: WarehouseRouteChildren = {
  WarehouseDispenseRoute: WarehouseDispenseRoute,
  WarehouseDrugRoute: WarehouseDrugRoute,
  WarehouseLossRoute: WarehouseLossRoute,
  WarehouseTransferRoute: WarehouseTransferRoute,
  WarehouseIndexRoute: WarehouseIndexRoute,
}

const WarehouseRouteWithChildren = WarehouseRoute._addFileChildren(
  WarehouseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  ArchiveRoute: ArchiveRouteWithChildren,
  KnowledgeRoute: KnowledgeRouteWithChildren,
  LoginRoute: LoginRoute,
  MRoute: MRouteWithChildren,
  OrganizationRoute: OrganizationRouteWithChildren,
  ProductionRoute: ProductionRouteWithChildren,
  SettingsRoute: SettingsRouteWithChildren,
  WarehouseRoute: WarehouseRouteWithChildren,
  WorkspaceRoute: WorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
